apiVersion: batch/v1
kind: Job
metadata:
  name: test-controller-job
  generateName: test-controller-job-
spec:
  template:
    spec:
      containers:
        - name: test-controller
          image: {{ .Values.controller.image }}
          imagePullPolicy: {{ .Values.controller.pullPolicy }}
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
      restartPolicy: Never
  backoffLimit: 0